import { starryTheme } from "@/styles/starryTheme";
import { useStereo } from "@/contexts/StereoContext";
import { responsiveStyles } from "@/styles/responsiveStyles";
import StarryBackground from "../StarryBackground";
import { useAppContext } from "@/contexts/AppContext";
import AuthButtons from "../auth/AuthButtons";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { isAndroidOrIOS } from "@/hooks/useDeviceDetection";

const LaunchScreen = () => {
  const navigate = useNavigate();
  const { initialPlay: initialPlayMusic } = useStereo();
  const { shouldAnimateStars, setSeenLaunchScreen } = useAppContext();
  const { pnAccessToken } = useAuth();

  if (isAndroidOrIOS()) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-900">
        <div className="text-white text-3xl font-bold text-center">
          Mobile devices are not supported
        </div>
      </div>
    );
  }

  const handleLaunch = () => {
    initialPlayMusic();
    setSeenLaunchScreen(true);
    navigate("/play");
  };

  return (
    <div style={starryTheme.container}>
      <div style={starryTheme.starryBackground} />
      <StarryBackground shouldAnimate={shouldAnimateStars} />
      <div
        style={{
          ...starryTheme.contentLeft,
          height: "100vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div className="flex flex-col items-center justify-center flex-1 relative">
          <div className="relative w-full h-96 mb-8">
            <img
              src="/ai_art/ship.webp"
              className="absolute w-[300px] -top-6 left-1/2 transform translate-x-2"
            />
            <img
              src="/ai_art/logo.webp"
              className="absolute w-[440px] top-48 left-1/2 transform -translate-x-1/2"
            />
          </div>

          {
            <div className="w-full max-w-4xl mx-auto bg-gray-800/80 rounded-lg shadow-xl p-6 border border-gray-700">
              <div
                className={`text-center text-gray-200 text-lg space-y-4 font-mono`}
                style={{ fontFamily: "IBM Plex Mono, monospace" }}
              >
                <p>
                  A collection of weird and spooky short stories, partly
                  generated by AI.
                </p>
                <p>
                  WARNING: creepy events and AI generated content lie in wait
                  ahead! Not suitable for those under the age of 13.
                </p>

                <p>
                  Feel free to adjust your headphones or volume control, but do
                  not attempt to adjust the picture.
                </p>
              </div>
            </div>
          }
          <div className="flex flex-row gap-4 m-8">
            <button
              onClick={handleLaunch}
              className={`${responsiveStyles.button.base} ${responsiveStyles.button.primary} ${responsiveStyles.padding.button} ${responsiveStyles.text.base}`}
            >
              Launch
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LaunchScreen;
